name: aclready_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.4
  - nodejs
  - pip
  - pip:
    - flask
    - flask_cors
    - jupyterlab # For convienence, this is not needed for application to run
    - langchain
    - langchain-chroma
    - langchain-community
    - langchain-text-splitters
    - langchain-openai
    - langchain-together
    - openai
    - pdfplumber
    - pylatexenc
    - python-dotenv
    - sentence-transformers
    - transformers


